@baseUrl = http://localhost:8080

### GET index.html
GET {{baseUrl}}/app/

### GET logo.png
GET {{baseUrl}}/app/assets/logo.png

### GET healthz
GET {{baseUrl}}/api/healthz

### GET metrics
GET {{baseUrl}}/admin/metrics

### POST reset
POST {{baseUrl}}/admin/reset

### POST /api/users
POST {{baseUrl}}/api/users

{
  "email": "user2@test.com",
  "password": "password2"
}

### Update User
PUT {{baseUrl}}/api/users
Authorization: Bearer <token>

{
  "email": "user1_modified@test.com",
  "password": "password2"
}

### Login
POST {{baseUrl}}/api/login

{
  "email": "user2@test.com",
  "password": "password2"
}

### Refresh
POST {{baseUrl}}/api/refresh
Authorization: Bearer <token>

### Revoke
POST {{baseUrl}}/api/revoke
Authorization: Bearer <token>

### POST /api/chirps valid
POST {{baseUrl}}/api/chirps
Authorization: Bearer <token>

{
  "body": "Hello, world 444"
}

### POST /api/chirps valid with word that get censored
POST {{baseUrl}}/api/chirps

{
  "body": "This is a kerfuffle opinion I need to share with the world",
  "user_id": "95a23ee1-4a82-4af4-b191-d928934aebdb"
}

### POST validate_chirp invalid, too long
POST {{baseUrl}}/api/chirps

{
  "body": "This is a long chirp, this is a long chirp, this is a long chirp, this is a long chirp, this is a long chirp, this is a long chirp, this is a long chirp, this is a long chirp",
  "user_id": "7c64575e-2cec-41c3-9aeb-b4a778ac816e"
}

### GET all chirps
GET {{baseUrl}}/api/chirps

### GET single chirp
@chirpID = 92b62c89-d46d-4206-9c96-a9d38fa59e04
GET {{baseUrl}}/api/chirps/{{chirpID}}

### DELETE a chirp
@chirpID2 = 740775c8-f48c-4562-acc9-841ccde2760b
DELETE {{baseUrl}}/api/chirps/{{chirpID2}}
Authorization: Bearer <token>

### Polka Webhook upgrade user
POST {{baseUrl}}/api/polka/webhooks

{
    "event": "user.upgraded",
    "data": {
        "user_id": "7645015b-5d72-490b-92f2-9583e76451df"
    }
}


